format_version: v1.0
type: UniqueComponent
attributes: {id: i2c2}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: '196'}
  - type: Integer
    attributes: {id: I2CS_RISE_TIME_CORE_TIMER_CNTS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: '12'}
  - type: Integer
    attributes: {id: I2CS_SETUP_TIME_CORE_TIMER_CNTS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: '4'}
  - type: Integer
    attributes: {id: I2C_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: '40000000'}
  - type: Long
    attributes: {id: I2C_CLOCK_SPEED}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '100000'}
  - type: Boolean
    attributes: {id: I2C_INCLUDE_FORCED_WRITE_API}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '455', y: '21', id: i2c2}
