files:
- generatedChecksum: C2B88D9215301ECE3DC36E4B82F2791C
  logicalPath: config\PIC32MX795F512L
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C2B88D9215301ECE3DC36E4B82F2791C
- generatedChecksum: FBEC42C553D81DA4D37B43D2FBDD4016
  logicalPath: config\PIC32MX795F512L
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 67AE8D3245D58C4E9EDF8476C7C43899
- generatedChecksum: 6922AEB99774B93365A20934F8562E62
  logicalPath: config\PIC32MX795F512L
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6922AEB99774B93365A20934F8562E62
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 652260DCDCCE4DC9B916FC87E4479BC2
  logicalPath: config\PIC32MX795F512L\peripheral\adc
  name: plib_adc.c
  physicalPath: peripheral\adc
  security: NON_SECURE
  type: SOURCE
  userChecksum: B16EF5086E0EB66FDE0C507554ED2DAB
- generatedChecksum: 9854678C3A3E4E9544EC7450ACBAE52A
  logicalPath: config\PIC32MX795F512L\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9854678C3A3E4E9544EC7450ACBAE52A
- generatedChecksum: B8C5B65EF693A3EA4566E395D2AE1BE4
  logicalPath: config\PIC32MX795F512L\peripheral\dmac
  name: plib_dmac.c
  physicalPath: peripheral\dmac
  security: NON_SECURE
  type: SOURCE
  userChecksum: B8C5B65EF693A3EA4566E395D2AE1BE4
- generatedChecksum: FCB09D7BE1B6A721446EAA5F18463398
  logicalPath: config\PIC32MX795F512L\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: FCB09D7BE1B6A721446EAA5F18463398
- generatedChecksum: 7CA027D423A7E49B06B116C350005FA1
  logicalPath: config\PIC32MX795F512L\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7CA027D423A7E49B06B116C350005FA1
- generatedChecksum: D5EBECC7B88C2322097297F636F85746
  logicalPath: config\PIC32MX795F512L\peripheral\i2c\master
  name: plib_i2c2_master.c
  physicalPath: peripheral\i2c\master
  security: NON_SECURE
  type: SOURCE
  userChecksum: D5EBECC7B88C2322097297F636F85746
- generatedChecksum: EEBEE814C5713B282725EF327FD884FD
  logicalPath: config\PIC32MX795F512L\peripheral\tmr1
  name: plib_tmr1.c
  physicalPath: peripheral\tmr1
  security: NON_SECURE
  type: SOURCE
  userChecksum: EEBEE814C5713B282725EF327FD884FD
- generatedChecksum: B67676CC0C0AA6C76103FFB2969A2E35
  logicalPath: config\PIC32MX795F512L\peripheral\tmr
  name: plib_tmr2.c
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: B67676CC0C0AA6C76103FFB2969A2E35
- generatedChecksum: 34B21F7FC4ED8582F6BDE8B7E913D8BA
  logicalPath: config\PIC32MX795F512L\peripheral\uart
  name: plib_uart2.c
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2537E1F0A3998E80A88CF3A1F6BD1F57
- generatedChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
  logicalPath: config\PIC32MX795F512L\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
- generatedChecksum: 6CD78EB1B8225D6AE86DF73CE24DED08
  logicalPath: config\PIC32MX795F512L
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 6CD78EB1B8225D6AE86DF73CE24DED08
- generatedChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
  logicalPath: config\PIC32MX795F512L
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
- generatedChecksum: E8917BB734DC71DCEBD331F58F060D11
  logicalPath: config\PIC32MX795F512L\peripheral\adc
  name: plib_adc.h
  physicalPath: peripheral\adc
  security: NON_SECURE
  type: HEADER
  userChecksum: E8917BB734DC71DCEBD331F58F060D11
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\PIC32MX795F512L\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 0B4F0EB2652222EDB94D733C95008D95
  logicalPath: config\PIC32MX795F512L\peripheral\dmac
  name: plib_dmac.h
  physicalPath: peripheral\dmac
  security: NON_SECURE
  type: HEADER
  userChecksum: 0B4F0EB2652222EDB94D733C95008D95
- generatedChecksum: 1BA4A111238723BF8148CF1BC7442A3C
  logicalPath: config\PIC32MX795F512L\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 1BA4A111238723BF8148CF1BC7442A3C
- generatedChecksum: 5530268A90550F6317461D486FDAE73F
  logicalPath: config\PIC32MX795F512L\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 5530268A90550F6317461D486FDAE73F
- generatedChecksum: E845D309D2BB0E88D676F1C5587D3A73
  logicalPath: config\PIC32MX795F512L\peripheral\i2c\master
  name: plib_i2c2_master.h
  physicalPath: peripheral\i2c\master
  security: NON_SECURE
  type: HEADER
  userChecksum: E845D309D2BB0E88D676F1C5587D3A73
- generatedChecksum: B963C6FE44292A1C4A14C3BA5BE95AEE
  logicalPath: config\PIC32MX795F512L\peripheral\i2c\master
  name: plib_i2c_master_common.h
  physicalPath: peripheral\i2c\master
  security: NON_SECURE
  type: HEADER
  userChecksum: B963C6FE44292A1C4A14C3BA5BE95AEE
- generatedChecksum: 32D7539D9231F3C159ABECE91A0281EA
  logicalPath: config\PIC32MX795F512L\peripheral\tmr1
  name: plib_tmr1.h
  physicalPath: peripheral\tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 32D7539D9231F3C159ABECE91A0281EA
- generatedChecksum: 69E7C8CDAB1B32838331EE261170CEA4
  logicalPath: config\PIC32MX795F512L\peripheral\tmr1
  name: plib_tmr1_common.h
  physicalPath: peripheral\tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 69E7C8CDAB1B32838331EE261170CEA4
- generatedChecksum: 612994C7F3C27F2CFA2621C1F65D4068
  logicalPath: config\PIC32MX795F512L\peripheral\tmr
  name: plib_tmr2.h
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 612994C7F3C27F2CFA2621C1F65D4068
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config\PIC32MX795F512L\peripheral\tmr
  name: plib_tmr_common.h
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: 53452ED8A95496907DF58F215C01E9C2
  logicalPath: config\PIC32MX795F512L\peripheral\uart
  name: plib_uart2.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 53452ED8A95496907DF58F215C01E9C2
- generatedChecksum: 903175300C64256E267D1DB8F91D7861
  logicalPath: config\PIC32MX795F512L\peripheral\uart
  name: plib_uart_common.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 903175300C64256E267D1DB8F91D7861
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\PIC32MX795F512L
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: 728A8885FAEA561A5BFCFC61F1F19DB0
  logicalPath: config\PIC32MX795F512L
  name: p32MX795F512L.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 728A8885FAEA561A5BFCFC61F1F19DB0
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/PIC32MX795F512L;../src/packs/PIC32MX795F512L_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/PIC32MX795F512L;../src/packs/PIC32MX795F512L_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
