files:
- generatedChecksum: C2B88D9215301ECE3DC36E4B82F2791C
  logicalPath: config\PIC32MX795F512L
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C2B88D9215301ECE3DC36E4B82F2791C
- generatedChecksum: 884DFDE10A995711401ADB05F6E96115
  logicalPath: config\PIC32MX795F512L
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 884DFDE10A995711401ADB05F6E96115
- generatedChecksum: D8C78EB4AF0DAF7C0DB28ED7B04624CD
  logicalPath: config\PIC32MX795F512L
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D8C78EB4AF0DAF7C0DB28ED7B04624CD
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: C9934611EE985FD35B73D6953FED7E08
  logicalPath: config\PIC32MX795F512L\peripheral\adc
  name: plib_adc.c
  physicalPath: peripheral\adc
  security: NON_SECURE
  type: SOURCE
  userChecksum: B16EF5086E0EB66FDE0C507554ED2DAB
- generatedChecksum: 9854678C3A3E4E9544EC7450ACBAE52A
  logicalPath: config\PIC32MX795F512L\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9854678C3A3E4E9544EC7450ACBAE52A
- generatedChecksum: A8F300D11FE7DF56876D5A5A59EEA498
  logicalPath: config\PIC32MX795F512L\peripheral\dmac
  name: plib_dmac.c
  physicalPath: peripheral\dmac
  security: NON_SECURE
  type: SOURCE
  userChecksum: A8F300D11FE7DF56876D5A5A59EEA498
- generatedChecksum: 92EF80CE487B8E716C16779C03DC5A0B
  logicalPath: config\PIC32MX795F512L\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 92EF80CE487B8E716C16779C03DC5A0B
- generatedChecksum: 7CA027D423A7E49B06B116C350005FA1
  logicalPath: config\PIC32MX795F512L\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7CA027D423A7E49B06B116C350005FA1
- generatedChecksum: EEBEE814C5713B282725EF327FD884FD
  logicalPath: config\PIC32MX795F512L\peripheral\tmr1
  name: plib_tmr1.c
  physicalPath: peripheral\tmr1
  security: NON_SECURE
  type: SOURCE
  userChecksum: EEBEE814C5713B282725EF327FD884FD
- generatedChecksum: B67676CC0C0AA6C76103FFB2969A2E35
  logicalPath: config\PIC32MX795F512L\peripheral\tmr
  name: plib_tmr2.c
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: B67676CC0C0AA6C76103FFB2969A2E35
- generatedChecksum: 57EF05ADB799DA5F66D269EF4EFEFF7B
  logicalPath: config\PIC32MX795F512L\peripheral\uart
  name: plib_uart2.c
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2537E1F0A3998E80A88CF3A1F6BD1F57
- generatedChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
  logicalPath: config\PIC32MX795F512L\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
- generatedChecksum: B8DA01DABCA10E924E6958BBFFA541B3
  logicalPath: config\PIC32MX795F512L
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: B8DA01DABCA10E924E6958BBFFA541B3
- generatedChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
  logicalPath: config\PIC32MX795F512L
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
- generatedChecksum: E8917BB734DC71DCEBD331F58F060D11
  logicalPath: config\PIC32MX795F512L\peripheral\adc
  name: plib_adc.h
  physicalPath: peripheral\adc
  security: NON_SECURE
  type: HEADER
  userChecksum: E8917BB734DC71DCEBD331F58F060D11
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\PIC32MX795F512L\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 0B4F0EB2652222EDB94D733C95008D95
  logicalPath: config\PIC32MX795F512L\peripheral\dmac
  name: plib_dmac.h
  physicalPath: peripheral\dmac
  security: NON_SECURE
  type: HEADER
  userChecksum: 0B4F0EB2652222EDB94D733C95008D95
- generatedChecksum: 1BA4A111238723BF8148CF1BC7442A3C
  logicalPath: config\PIC32MX795F512L\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 1BA4A111238723BF8148CF1BC7442A3C
- generatedChecksum: 5530268A90550F6317461D486FDAE73F
  logicalPath: config\PIC32MX795F512L\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 5530268A90550F6317461D486FDAE73F
- generatedChecksum: 32D7539D9231F3C159ABECE91A0281EA
  logicalPath: config\PIC32MX795F512L\peripheral\tmr1
  name: plib_tmr1.h
  physicalPath: peripheral\tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 32D7539D9231F3C159ABECE91A0281EA
- generatedChecksum: 69E7C8CDAB1B32838331EE261170CEA4
  logicalPath: config\PIC32MX795F512L\peripheral\tmr1
  name: plib_tmr1_common.h
  physicalPath: peripheral\tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 69E7C8CDAB1B32838331EE261170CEA4
- generatedChecksum: 612994C7F3C27F2CFA2621C1F65D4068
  logicalPath: config\PIC32MX795F512L\peripheral\tmr
  name: plib_tmr2.h
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 612994C7F3C27F2CFA2621C1F65D4068
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config\PIC32MX795F512L\peripheral\tmr
  name: plib_tmr_common.h
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: C57271B930D8F151C50DB4E9B39B41B5
  logicalPath: config\PIC32MX795F512L\peripheral\uart
  name: plib_uart2.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: C57271B930D8F151C50DB4E9B39B41B5
- generatedChecksum: 903175300C64256E267D1DB8F91D7861
  logicalPath: config\PIC32MX795F512L\peripheral\uart
  name: plib_uart_common.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 903175300C64256E267D1DB8F91D7861
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\PIC32MX795F512L
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: 728A8885FAEA561A5BFCFC61F1F19DB0
  logicalPath: config\PIC32MX795F512L
  name: p32MX795F512L.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 728A8885FAEA561A5BFCFC61F1F19DB0
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/PIC32MX795F512L;../src/packs/PIC32MX795F512L_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/PIC32MX795F512L;../src/packs/PIC32MX795F512L_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
