format_version: v1.0
type: UniqueComponent
attributes: {id: tmr1}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: TCON_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr1, value: '32'}
  - type: Integer
    attributes: {id: TIMER1_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr1, value: '625000'}
  - type: Long
    attributes: {id: TIMER1_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr1, value: '62499'}
  - type: KeyValueSet
    attributes: {id: TIMER1_PRE_SCALER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Float
    attributes: {id: TIMER1_TIME_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '104.856'}
    - type: Values
      children:
      - type: User
        attributes: {value: '100.0'}
  - type: Integer
    attributes: {id: TMR1_PRESCALER_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr1, value: '64'}
- type: ElementPosition
  attributes: {x: '801', y: '173', id: tmr1}
