#ifndef __HARDWARE_PROFILE_H
#define __HARDWARE_PROFILE_H


#define HEARTBEAT_LAT  _RE3
#define HEARTBEAT_TRIS  _TRISE3
#define FLIP_HEARTBEAT_LED() PORTEINV = 0x0008
#define REDLED_OFF() PORTESET = 0x0008
#define REDLED_ON() PORTECLR = 0x0008


#define GREENLED_LAT  _RE2
#define GREENLED_TRIS  _TRISE2
#define FLIP_GREEN_LED() PORTEINV = 0x0004
#define GREENLED_OFF() PORTESET = 0x0004
#define GREENLED_ON() PORTECLR = 0x0004

#define BLUELED_LAT  _RE1
#define BLUELED_TRIS  _TRISE1
#define FLIP_BLUE_LED() PORTEINV = 0x0002
#define BLUELED_ON() PORTECLR = 0x0002
#define BLUELED_OFF() PORTESET = 0x0002


#define YELLOWLED_LAT  _RE0
#define YELLOWLED_TRIS  _TRISE0
#define FLIP_YELLOW_LED() PORTEINV = 0x0001
#define YELLOWLED_ON() PORTECLR = 0x0001
#define YELLOWLED_OFF() PORTESET = 0x0001

#define SWITCH_TRIS _TRISE4
#define SWITCH_PORT _RE4

#define USERBUTTON1_TRIS _TRISE6
#define USERBUTTON1_PORT _RE6

#define USERBUTTON2_TRIS _TRISE5
#define USERBUTTON2_PORT _RE5

#define BUTTON1_DEBOUNCE_COUNTS 100
#define BUTTON2_DEBOUNCE_COUNTS 100

#define IDSELECTOR1_TRIS _TRISD12
#define IDSELECTOR1_PORT _RD12
#define IDSELECTOR2_TRIS _TRISD13
#define IDSELECTOR2_PORT _RD13
#define IDSELECTOR4_TRIS _TRISD14
#define IDSELECTOR4_PORT _RD14
#define IDSELECTOR8_TRIS _TRISD15
#define IDSELECTOR8_PORT _RD15
#define SETIDSELECTOR_TRIS() TRISDSET = 0x0000F000
#define GETIDSELECTOR_VALUE() ((~PORTD & 0xF000) >> 12)

#define RX485_ENABLE_DELAY() Delay10us(10)
#define RX485_DISABLE_DELAY() Delay10us(50)
#define RX485_ENABLE_SEND() _LATF13=1;Nop();Nop();RX485_ENABLE_DELAY()
#define RX485_DISABLE_SEND() RX485_DISABLE_DELAY();_LATF13=0;Nop();Nop();


#define RX485_SEND_TRIS _TRISF13
#define RX485_SEND_TRIS2 _TRISG15

#endif /* _EXAMPLE_FILE_NAME_H */

